CREATE SCHEMA umls;

use umls;

CREATE TABLE cui_terms (
cui BIGINT NOT NULL,
rindex INT(128) NOT NULL,
tcount INT(128) NOT NULL,
text VARCHAR(255) NOT NULL,
rword VARCHAR(48) NOT NULL
);
CREATE INDEX idx_cui_terms ON cui_terms (rword);

CREATE TABLE TUI (
cui BIGINT NOT NULL,
tui INT(128) NOT NULL
);
CREATE INDEX idx_tui ON TUI (cui);

CREATE TABLE PREFTERM (
cui BIGINT NOT NULL,
prefterm VARCHAR(511) NOT NULL
);
CREATE INDEX idx_prefterm ON PREFTERM (cui);

CREATE TABLE RXNORM (
cui BIGINT NOT NULL,
rxnorm BIGINT NOT NULL
);
CREATE INDEX idx_rxnorm ON RXNORM (cui);

CREATE TABLE SNOMEDCT_US (
cui BIGINT NOT NULL,
snomedct_us BIGINT NOT NULL
);
CREATE INDEX idx_snomedct_us ON SNOMEDCT_US (cui);