CREATE SCHEMA umls;

use umls;

CREATE TABLE CUI_TERMS (
  CUI BIGINT NOT NULL,
  RINDEX INT(128) NOT NULL,
  TCOUNT INT(128) NOT NULL,
  TEXT VARCHAR(255) NOT NULL,
  RWORD VARCHAR(48) NOT NULL
);
CREATE INDEX IDX_CUI_TERMS ON CUI_TERMS (RWORD);

CREATE TABLE TUI (
  CUI BIGINT NOT NULL,
  TUI INT(128) NOT NULL
);
CREATE INDEX IDX_TUI ON TUI (CUI);

CREATE TABLE PREFTERM (
  CUI BIGINT NOT NULL,
  PREFTERM VARCHAR(511) NOT NULL
);
CREATE INDEX IDX_PREFTERM ON PREFTERM (CUI);

CREATE TABLE RXNORM (
  CUI BIGINT NOT NULL,
  RXNORM BIGINT NOT NULL
);
CREATE INDEX IDX_RXNORM ON RXNORM (CUI);

CREATE TABLE SNOMEDCT_US (
  CUI BIGINT NOT NULL,
  SNOMEDCT_US BIGINT NOT NULL
);
CREATE INDEX IDX_SNOMEDCT_US ON SNOMEDCT_US (CUI);

